// packages/react-app/src/App.jsx
import { useEffect, useState } from "react";
import { notiBloc } from "../../core-lib/src/blocs/notifications/noti.bloc";
import "./App.css";
import reactLogo from "./assets/react.svg";
import viteLogo from "/vite.svg";
import '../../core-ui/src/my-element'

function App() {
  useEffect(() => {
    notiBloc.subscribe((state) => {
      console.log(JSON.stringify(state));
    });
  }, []);

  notiBloc.showInfo("Se mostrará?");

  const [count, setCount] = useState(0);

  console.log(notiBloc.getState());

  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <my-element></my-element>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.jsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
    </>
  );
}

export default App;

// packages/vue-app/src/App.vue
<script setup>
import HelloWorld from './components/HelloWorld.vue'
import { onMounted } from 'vue';
import { notiBloc } from "../../core-lib/src/blocs/notifications/noti.bloc";
import '../../core-ui/src/my-element'

onMounted(() => {
  notiBloc.subscribe((state) => {
      console.log(JSON.stringify(state));
    });

    notiBloc.showInfo("Se mostrará?");
});
</script>

<template>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <my-element></my-element>
  <HelloWorld msg="Vite + Vue" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
